---
# tasks file for apache
- name: install pkg
  yum:
    name:
      - "{{web_pkg}}"
      - "{{fw_pkg}}"
    state: latest
- name: srv
  service:
    name: "{{item}}"
    state: started
    enabled: yes
  loop:
    - "{{web_svc}}"
    - "{{fw_svc}}"
- name: fw
  firewalld:
    service: http
    permanent: true
    state: enabled
    immediate: true
- name: template
  template:
    src: index.html.j2
    dest: "{{web_root}}/index.html"
    mode: 0644

