---
- name: mysql repository
  hosts: all
  become: true
  tasks:
  - name: rpm key
    rpm_key:
      key: http://repo.mysql.com/RPM-GPG-KEY-mysql
      state: present
    when: ( 'proxy' in group_names )
  - name: repository
    yum_repository:
      name: mysql80-community
      file: mysql80-community
      description: "MySQL 8.0 YUM Repo"
      baseurl: http://repo.mysql.com/yum/mysql-8.0-community/el/8/x86_64/.
      gpgcheck: true
      gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
      state: present
      enabled: yes 
    when: ( 'proxy' in group_names )
