---
#ansible-galaxy role search --author geerlingguy haproxy
#ansible-galaxy role install geerlingguy.haproxy
- name: haproxy
  hosts: all
  become: true
  roles:
    - role: geerlingguy.haproxy
      haproxy_frontend_port: 8080
      haproxy_backend_mode: 'http'
      haproxy_backend_balance_method: 'roundrobin'
      haproxy_backend_servers:
        - name: node1
          address: 192.168.33.12:80
        - name: node2
          address: 192.168.33.13:80
  tasks:
    - name: fw installed
      yum:
        name: firewalld
        state: latest
    - name: svc fw up
      service:
        name: firewalld
        state: started
        enabled: yes
    - name: allow http in fw
      firewalld:
        #service: http
        port: 8080/tcp
        permanent: yes
        immediate: yes
        state: enabled
