---
- name: selinux
  hosts: all
  become: true
  roles:
    - role: linux-system-roles.selinux 
      vars:
        selinux_booleans:
          - name: 'httpd_can_network_connect'
            state: true
            persistent: true
