---
- name: system control
  hosts: all
  vars:
    ram_mb: 700
  tasks:
  - name: ensure server meets mem req
    fail:
      msg: "server must have at least {{ram_mb}}"
    when: ansible_memtotal_mb < ram_mb
  - name: conf swappiness
    become: true
    sysctl:
      name: vm.swappiness
      value: '10'
      sysctl_set: true
      reload: true

