---
- name: users
  hosts: all
  become: yes
  vars_files:
    - user_list.yml
  tasks:
    - name: create groups
      group:
        name: "{{item}}"
        state: present
      loop:
        - admin
        - members
    - name: ID start 1 on proxy
      user:
        name: "{{item.username}}"
        shell: /bin/bash
        groups: "{{item.group}}"
        append: yes
        uid: "{{item.uid}}"
        password: "{{ item.password | password_hash('sha256')}}"
      loop: "{{ users }}"
      when: ( 'proxy' in group_names ) and ( item.uid|string|first == '1' )
    - name: ID start 2 on webserver
      user:
        name: "{{item.username}}"
        shell: /bin/bash
        groups: "{{item.group}}"
        append: yes
        uid: "{{item.uid}}"
        password: "{{ item.password | password_hash('sha256')}}"
      loop: "{{ users }}"
      when: ( 'webserver' in group_names ) and ( item.uid|string|first == '2' )
